//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using JabbR.Infrastructure;

namespace JabbR.Models
{
    public partial class ChatRoom
    {

         public ChatRoom()
        {
            Owners = new SafeCollection<ChatUser>();
            Messages = new SafeCollection<ChatMessage>();
            Users = new SafeCollection<ChatUser>();
            AllowedUsers = new SafeCollection<ChatUser>();
        }
    
        public int Key { get; set; }
        public Nullable<System.DateTime> LastNudged { get; set; }
        public string Name { get; set; }
        public Nullable<int> Creator_Key { get; set; }
        public bool Private { get; set; }
        public string InviteCode { get; set; }
        public bool Closed { get; set; }
        public string Topic { get; set; }
        public string Welcome { get; set; }
        public System.Guid Request_Id { get; set; }

        public virtual ICollection<ChatUser> Owners { get; set; } 
    
        public virtual ICollection<ChatMessage> Messages { get; set; }
        public virtual ChatUser Creator { get; set; }
        public virtual ICollection<ChatUser> Users { get; set; }
        public virtual ICollection<ChatUser> AllowedUsers { get; set; }
    }
    
}
