//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace JabbR.Models
{
    public partial class ChatMessage
    {
        public int Key { get; set; }
        public string Content { get; set; }
        public string Id { get; set; }
        public System.DateTimeOffset When { get; set; }
        public Nullable<int> Room_Key { get; set; }
        public Nullable<int> User_Key { get; set; }
    
        public virtual ChatRoom Room { get; set; }
        public virtual ChatUser User { get; set; }
    }
    
}
