//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace JabbR.Models
{
    public partial class Member_CreditAccount
    {
        public int Id { get; set; }
        public int Member_Id { get; set; }
        public decimal Balance { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual Member Member { get; set; }
    }
    
}
