//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace JabbR.Models
{
    public partial class Chat_Request
    {
        public int Id { get; set; }
        public int RequestById { get; set; }
        public string RequestByKey { get; set; }
        public int RequestedId { get; set; }
        public string RequestedKey { get; set; }
        public Nullable<int> ResultEnum { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public System.Guid Guid { get; set; }
        public bool HasResponde { get; set; }
        public bool IsActive { get; set; }
        public bool IsVideoOn { get; set; }
    }
    
}
