//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace JabbR.Models
{
    public partial class ChatRoom
    {
        public ChatRoom()
        {
            this.Messages = new HashSet<ChatMessage>();
            this.Users = new HashSet<ChatUser>();
            this.AllowedUsers = new HashSet<ChatUser>();
        }
    
        public int Key { get; set; }
        public Nullable<System.DateTime> LastNudged { get; set; }
        public string Name { get; set; }
        public Nullable<int> Creator_Key { get; set; }
        public bool Private { get; set; }
        public string InviteCode { get; set; }
        public bool Closed { get; set; }
        public string Topic { get; set; }
        public string Welcome { get; set; }
        public System.Guid Request_Id { get; set; }
    
        public virtual ICollection<ChatMessage> Messages { get; set; }
        public virtual ChatUser Creator { get; set; }
        public virtual ICollection<ChatUser> Users { get; set; }
        public virtual ICollection<ChatUser> AllowedUsers { get; set; }
    }
    
}
