//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace JabbR.Models
{
    public partial class ChatClient
    {
        public int Key { get; set; }
        public string Id { get; set; }
        public int User_Key { get; set; }
        public string UserAgent { get; set; }
        public System.DateTimeOffset LastActivity { get; set; }
    
        public virtual ChatUser User { get; set; }
    }
    
}
